
// Generated by Cadence Encounter(R) RTL Compiler RC11.22 - v11.20-s017_1

// Verification Directory fv/SARTimerVerilog 

module SARTimerVerilog_TIMER5(Reset, ClockT, StateP, Inc, Dcr, Ready,
     TimerOut, FlagConv);
  input Reset, ClockT, Inc, Dcr;
  input [1:0] StateP;
  output Ready, FlagConv;
  output [4:0] TimerOut;
  wire Reset, ClockT, Inc, Dcr;
  wire [1:0] StateP;
  wire Ready, FlagConv;
  wire [4:0] TimerOut;
  wire [4:0] TempTMR;
  wire FlagTMR, N0, N1, N2, N3, N4, N5, N6;
  wire N7, N8, N9, N10, N11, N12, N13, N14;
  wire N15, N17, N18, N22, N23, N24, N25, N28;
  wire N29, N30, N32, N34, N35, N36, N37, N38;
  wire N39, N40, N41, N53, N54;
  QDFFRBS \TimerOut_reg[0] (.RB (N41), .CK (ClockT), .D (N35), .Q
       (TimerOut[0]));
  QDFFRBS \TimerOut_reg[1] (.RB (N41), .CK (ClockT), .D (N39), .Q
       (TimerOut[1]));
  QDFFRBS \TimerOut_reg[2] (.RB (N41), .CK (ClockT), .D (N40), .Q
       (TimerOut[2]));
  QDFFRBS \TimerOut_reg[3] (.RB (N41), .CK (ClockT), .D (N37), .Q
       (TimerOut[3]));
  QDFFRBS \TimerOut_reg[4] (.RB (N41), .CK (ClockT), .D (N36), .Q
       (TimerOut[4]));
  QDFFRBS FlagTMR_reg(.RB (N41), .CK (ClockT), .D (N34), .Q (FlagTMR));
  MXL2HS g541(.S (N38), .A (N15), .B (N0), .OB (N40));
  MXL2HS g540(.S (N38), .A (N10), .B (N4), .OB (N39));
  MXL2HS g542(.S (N38), .A (N25), .B (N5), .OB (N37));
  MXL2HS g543(.S (N38), .A (N7), .B (N3), .OB (N36));
  MXL2HS g544(.S (N38), .A (N11), .B (N2), .OB (N35));
  QDFFRBN \TempTMR_reg[2] (.RB (N41), .CK (ClockT), .D (N54), .Q
       (TempTMR[2]));
  QDFFRBN \TempTMR_reg[3] (.RB (N41), .CK (ClockT), .D (N53), .Q
       (TempTMR[3]));
  QDFFRBN \TempTMR_reg[4] (.RB (N41), .CK (ClockT), .D (N28), .Q
       (TempTMR[4]));
  QDFFRBP \TempTMR_reg[1] (.RB (N41), .CK (ClockT), .D (N29), .Q
       (TempTMR[1]));
  QDFFRBP \TempTMR_reg[0] (.RB (N41), .CK (ClockT), .D (N30), .Q
       (TempTMR[0]));
  ND2 g548(.I1 (N38), .I2 (N23), .O (N34));
  QDFFRBS Ready_reg(.RB (N41), .CK (ClockT), .D (N32), .Q (Ready));
  NR2 g549(.I1 (TempTMR[0]), .I2 (N32), .O (N30));
  NR2 g550(.I1 (N12), .I2 (N32), .O (N29));
  NR2 g551(.I1 (N22), .I2 (N32), .O (N28));
  INV4 g552(.I (N32), .O (N38));
  ND2F g553(.I1 (N18), .I2 (N24), .O (N32));
  OR2 g560(.I1 (FlagTMR), .I2 (N23), .O (N24));
  AOI12S g555(.A1 (TempTMR[4]), .B1 (N17), .B2 (TempTMR[3]), .O (N22));
  INV1S g562(.I (N23), .O (FlagConv));
  ND2P g563(.I1 (N13), .I2 (N9), .O (N23));
  ND3P g554(.I1 (N17), .I2 (TempTMR[4]), .I3 (TempTMR[3]), .O (N18));
  NR2P g561(.I1 (N15), .I2 (N14), .O (N17));
  ND3P g564(.I1 (N8), .I2 (N6), .I3 (N1), .O (N13));
  AOI22S g566(.A1 (N11), .A2 (TempTMR[1]), .B1 (N10), .B2 (TempTMR[0]),
       .O (N12));
  AOI12S g565(.A1 (Reset), .B1 (StateP[0]), .B2 (StateP[1]), .O (N9));
  NR2P g567(.I1 (Dcr), .I2 (Inc), .O (N8));
  ND2P g568(.I1 (TempTMR[1]), .I2 (TempTMR[0]), .O (N14));
  INV1S g573(.I (TempTMR[4]), .O (N7));
  INV2 g581(.I (StateP[0]), .O (N6));
  INV1S g572(.I (TimerOut[3]), .O (N5));
  INV1S g570(.I (TimerOut[1]), .O (N4));
  INV1S g577(.I (TempTMR[3]), .O (N25));
  INV1S g575(.I (TimerOut[4]), .O (N3));
  INV1S g580(.I (TimerOut[0]), .O (N2));
  INV1S g578(.I (TempTMR[1]), .O (N10));
  INV1 g579(.I (StateP[1]), .O (N1));
  INV1S g574(.I (TempTMR[0]), .O (N11));
  INV1S g569(.I (TimerOut[2]), .O (N0));
  INV2 g576(.I (TempTMR[2]), .O (N15));
  INV1S g571(.I (Reset), .O (N41));
  MUXB2 g2(.S (N17), .A (TempTMR[3]), .B (N25), .EB (N32), .O (N53));
  MUXB2 g594(.S (N14), .A (N15), .B (TempTMR[2]), .EB (N32), .O (N54));
endmodule

