
// Generated by Cadence Encounter(R) RTL Compiler RC11.22 - v11.20-s017_1

// Verification Directory fv/SARTimerVerilog 

module SARTimerVerilog_TIMER8(Reset, ClockT, StateP, Inc, Dcr, Ready,
     TimerOut, FlagConv);
  input Reset, ClockT, Inc, Dcr;
  input [1:0] StateP;
  output Ready, FlagConv;
  output [7:0] TimerOut;
  wire Reset, ClockT, Inc, Dcr;
  wire [1:0] StateP;
  wire Ready, FlagConv;
  wire [7:0] TimerOut;
  wire [7:0] TempTMR;
  wire FlagTMR, N0, N1, N2, N3, N4, N5, N6;
  wire N7, N8, N9, N10, N11, N12, N13, N14;
  wire N15, N16, N17, N18, N19, N20, N21, N22;
  wire N23, N24, N25, N27, N28, N29, N30, N32;
  wire N34, N36, N37, N38, N39, N40, N41, N42;
  wire N43, N45, N46, N48, N49, N51, N52, N53;
  wire N54, N55, N56, N57, N58, N59, N60, N61;
  wire N62, N63, N78, N79;
  QDFFRBS \TimerOut_reg[7] (.RB (N63), .CK (ClockT), .D (N53), .Q
       (TimerOut[7]));
  QDFFRBS \TimerOut_reg[0] (.RB (N63), .CK (ClockT), .D (N62), .Q
       (TimerOut[0]));
  QDFFRBS \TimerOut_reg[1] (.RB (N63), .CK (ClockT), .D (N61), .Q
       (TimerOut[1]));
  QDFFRBS \TimerOut_reg[2] (.RB (N63), .CK (ClockT), .D (N59), .Q
       (TimerOut[2]));
  QDFFRBS \TimerOut_reg[3] (.RB (N63), .CK (ClockT), .D (N58), .Q
       (TimerOut[3]));
  QDFFRBS \TimerOut_reg[4] (.RB (N63), .CK (ClockT), .D (N57), .Q
       (TimerOut[4]));
  QDFFRBS \TimerOut_reg[5] (.RB (N63), .CK (ClockT), .D (N56), .Q
       (TimerOut[5]));
  QDFFRBS \TimerOut_reg[6] (.RB (N63), .CK (ClockT), .D (N55), .Q
       (TimerOut[6]));
  QDFFRBS FlagTMR_reg(.RB (N63), .CK (ClockT), .D (N54), .Q (FlagTMR));
  QDFFRBP \TempTMR_reg[6] (.RB (N63), .CK (ClockT), .D (N43), .Q
       (TempTMR[6]));
  QDFFRBN \TempTMR_reg[7] (.RB (N63), .CK (ClockT), .D (N51), .Q
       (TempTMR[7]));
  QDFFRBP \TempTMR_reg[2] (.RB (N63), .CK (ClockT), .D (N79), .Q
       (TempTMR[2]));
  QDFFRBP \TempTMR_reg[5] (.RB (N63), .CK (ClockT), .D (N45), .Q
       (TempTMR[5]));
  QDFFRBN \TempTMR_reg[3] (.RB (N63), .CK (ClockT), .D (N52), .Q
       (TempTMR[3]));
  QDFFRBP \TempTMR_reg[0] (.RB (N63), .CK (ClockT), .D (N49), .Q
       (TempTMR[0]));
  QDFFRBP \TempTMR_reg[4] (.RB (N63), .CK (ClockT), .D (N78), .Q
       (TempTMR[4]));
  QDFFRBP \TempTMR_reg[1] (.RB (N63), .CK (ClockT), .D (N48), .Q
       (TempTMR[1]));
  QDFFRBS Ready_reg(.RB (N63), .CK (ClockT), .D (N60), .Q (Ready));
  MXL2HS g771(.S (N60), .A (N0), .B (N19), .OB (N62));
  MXL2HS g772(.S (N60), .A (N7), .B (N18), .OB (N61));
  MXL2HS g773(.S (N60), .A (N6), .B (N25), .OB (N59));
  MXL2HS g774(.S (N60), .A (N9), .B (N5), .OB (N58));
  MXL2HS g775(.S (N60), .A (N1), .B (N30), .OB (N57));
  MXL2HS g776(.S (N60), .A (N8), .B (N38), .OB (N56));
  MXL2HS g777(.S (N60), .A (N10), .B (N42), .OB (N55));
  ND2 g781(.I1 (N46), .I2 (N29), .O (N54));
  MXL2HS g770(.S (N60), .A (N3), .B (N4), .OB (N53));
  NR2 g751(.I1 (N34), .I2 (N60), .O (N52));
  NR2 g761(.I1 (N41), .I2 (N60), .O (N51));
  NR2 g782(.I1 (TempTMR[0]), .I2 (N60), .O (N49));
  NR2 g783(.I1 (N20), .I2 (N60), .O (N48));
  NR2 g750(.I1 (N40), .I2 (N60), .O (N45));
  MUXB2 g746(.S (N39), .A (TempTMR[6]), .B (N42), .EB (N60), .O (N43));
  INV2 g785(.I (N60), .O (N46));
  ND2F g786(.I1 (N28), .I2 (N36), .O (N60));
  AOI12S g768(.A1 (TempTMR[7]), .B1 (N32), .B2 (N17), .O (N41));
  XOR2HS g769(.I1 (TempTMR[5]), .I2 (N37), .O (N40));
  NR2 g780(.I1 (N38), .I2 (N37), .O (N39));
  ND2P g789(.I1 (FlagConv), .I2 (N2), .O (N36));
  XNR2HS g762(.I1 (TempTMR[3]), .I2 (N24), .O (N34));
  INV1S g788(.I (N37), .O (N32));
  INV1S g794(.I (FlagConv), .O (N29));
  ND2T g793(.I1 (N22), .I2 (N27), .O (N28));
  ND2P g792(.I1 (N27), .I2 (TempTMR[4]), .O (N37));
  NR2T g795(.I1 (N21), .I2 (N15), .O (FlagConv));
  NR2F g799(.I1 (N14), .I2 (N12), .O (N27));
  NR2 g790(.I1 (N25), .I2 (N23), .O (N24));
  NR2P g796(.I1 (N11), .I2 (N16), .O (N22));
  ND2 g798(.I1 (N13), .I2 (N63), .O (N21));
  AOI22S g800(.A1 (N19), .A2 (TempTMR[1]), .B1 (N18), .B2 (TempTMR[0]),
       .O (N20));
  INV1S g803(.I (N16), .O (N17));
  NR4 g797(.I1 (Inc), .I2 (StateP[1]), .I3 (Dcr), .I4 (StateP[0]), .O
       (N15));
  ND2P g806(.I1 (TempTMR[0]), .I2 (TempTMR[2]), .O (N14));
  ND2 g807(.I1 (StateP[0]), .I2 (StateP[1]), .O (N13));
  ND2P g805(.I1 (TempTMR[1]), .I2 (TempTMR[3]), .O (N12));
  ND2P g801(.I1 (TempTMR[4]), .I2 (TempTMR[7]), .O (N11));
  ND2 g802(.I1 (TempTMR[1]), .I2 (TempTMR[0]), .O (N23));
  ND2 g804(.I1 (TempTMR[5]), .I2 (TempTMR[6]), .O (N16));
  INV1S g815(.I (TempTMR[6]), .O (N42));
  INV1S g812(.I (TimerOut[6]), .O (N10));
  INV1S g811(.I (TimerOut[3]), .O (N9));
  INV1S g809(.I (TempTMR[2]), .O (N25));
  INV1S g820(.I (TimerOut[5]), .O (N8));
  INV1S g819(.I (TempTMR[4]), .O (N30));
  INV1S g816(.I (Reset), .O (N63));
  INV1S g824(.I (TimerOut[1]), .O (N7));
  INV1S g817(.I (TimerOut[2]), .O (N6));
  INV1S g818(.I (TempTMR[0]), .O (N19));
  INV1S g823(.I (TempTMR[3]), .O (N5));
  INV1S g825(.I (TempTMR[7]), .O (N4));
  INV1S g814(.I (TempTMR[1]), .O (N18));
  INV1S g808(.I (TimerOut[7]), .O (N3));
  INV1S g821(.I (FlagTMR), .O (N2));
  INV1S g810(.I (TimerOut[4]), .O (N1));
  INV1S g822(.I (TimerOut[0]), .O (N0));
  INV1S g813(.I (TempTMR[5]), .O (N38));
  MUXB2 g2(.S (N27), .A (TempTMR[4]), .B (N30), .EB (N60), .O (N78));
  MUXB2 g844(.S (N23), .A (N25), .B (TempTMR[2]), .EB (N60), .O (N79));
endmodule

