
// Generated by Cadence Encounter(R) RTL Compiler RC11.22 - v11.20-s017_1

// Verification Directory fv/SARTimerVerilog 

module SARTimerVerilog_TIMER4(Reset, ClockT, StateP, Inc, Dcr, Ready,
     TimerOut, FlagConv);
  input Reset, ClockT, Inc, Dcr;
  input [1:0] StateP;
  output Ready, FlagConv;
  output [3:0] TimerOut;
  wire Reset, ClockT, Inc, Dcr;
  wire [1:0] StateP;
  wire Ready, FlagConv;
  wire [3:0] TimerOut;
  wire [3:0] TempTMR;
  wire FlagTMR, N0, N1, N2, N3, N4, N5, N6;
  wire N7, N8, N9, N10, N11, N12, N14, N15;
  wire N17, N18, N19, N20, N21, N22, N23, N24;
  wire N26, N27, N28, N30, N31, N42;
  QDFFRBS \TimerOut_reg[0] (.RB (N31), .CK (ClockT), .D (N28), .Q
       (TimerOut[0]));
  QDFFRBS \TimerOut_reg[2] (.RB (N31), .CK (ClockT), .D (N30), .Q
       (TimerOut[2]));
  QDFFRBS \TimerOut_reg[3] (.RB (N31), .CK (ClockT), .D (N26), .Q
       (TimerOut[3]));
  QDFFRBS \TimerOut_reg[1] (.RB (N31), .CK (ClockT), .D (N24), .Q
       (TimerOut[1]));
  QDFFRBN FlagTMR_reg(.RB (N31), .CK (ClockT), .D (N42), .Q (FlagTMR));
  QDFFRBN \TempTMR_reg[2] (.RB (N31), .CK (ClockT), .D (N23), .Q
       (TempTMR[2]));
  QDFFRBN \TempTMR_reg[3] (.RB (N31), .CK (ClockT), .D (N18), .Q
       (TempTMR[3]));
  QDFFRBP \TempTMR_reg[1] (.RB (N31), .CK (ClockT), .D (N20), .Q
       (TempTMR[1]));
  QDFFRBP \TempTMR_reg[0] (.RB (N31), .CK (ClockT), .D (N21), .Q
       (TempTMR[0]));
  MXL2HS g419(.S (N27), .A (N1), .B (N22), .OB (N30));
  MXL2HS g417(.S (N27), .A (N0), .B (N2), .OB (N28));
  MXL2HS g416(.S (N27), .A (N3), .B (N17), .OB (N26));
  MXL2HS g418(.S (N27), .A (N4), .B (N19), .OB (N24));
  MUXB2 g421(.S (N9), .A (N22), .B (TempTMR[2]), .EB (N27), .O (N23));
  QDFFRBS Ready_reg(.RB (N31), .CK (ClockT), .D (N27), .Q (Ready));
  NR2 g423(.I1 (TempTMR[0]), .I2 (N27), .O (N21));
  MUXB2 g424(.S (TempTMR[0]), .A (TempTMR[1]), .B (N19), .EB (N27), .O
       (N20));
  AOI12S g425(.A1 (N27), .B1 (N11), .B2 (N17), .O (N18));
  ND2T g427(.I1 (N12), .I2 (N15), .O (N27));
  OR2 g431(.I1 (FlagTMR), .I2 (N14), .O (N15));
  INV1S g432(.I (N14), .O (FlagConv));
  ND2P g428(.I1 (N10), .I2 (TempTMR[3]), .O (N12));
  ND2P g433(.I1 (N8), .I2 (N7), .O (N14));
  INV1S g429(.I (N10), .O (N11));
  NR2P g430(.I1 (N22), .I2 (N9), .O (N10));
  ND2 g434(.I1 (N5), .I2 (N6), .O (N8));
  AOI12S g435(.A1 (Reset), .B1 (StateP[0]), .B2 (StateP[1]), .O (N7));
  ND2 g438(.I1 (TempTMR[1]), .I2 (TempTMR[0]), .O (N9));
  NR2 g436(.I1 (Inc), .I2 (Dcr), .O (N6));
  NR2 g437(.I1 (StateP[0]), .I2 (StateP[1]), .O (N5));
  INV1S g444(.I (TempTMR[3]), .O (N17));
  INV1S g446(.I (TimerOut[1]), .O (N4));
  INV1S g440(.I (TimerOut[3]), .O (N3));
  INV2 g441(.I (TempTMR[2]), .O (N22));
  INV1S g443(.I (TempTMR[1]), .O (N19));
  INV1S g447(.I (TempTMR[0]), .O (N2));
  INV1S g442(.I (TimerOut[2]), .O (N1));
  INV1S g439(.I (Reset), .O (N31));
  INV1S g445(.I (TimerOut[0]), .O (N0));
  OR2B1S g2(.I1 (N27), .B1 (N14), .O (N42));
endmodule

