
// Generated by Cadence Encounter(R) RTL Compiler RC11.22 - v11.20-s017_1

// Verification Directory fv/SARTimerVerilog 

module SARTimerVerilog_TIMER7(Reset, ClockT, StateP, Inc, Dcr, Ready,
     TimerOut, FlagConv);
  input Reset, ClockT, Inc, Dcr;
  input [1:0] StateP;
  output Ready, FlagConv;
  output [6:0] TimerOut;
  wire Reset, ClockT, Inc, Dcr;
  wire [1:0] StateP;
  wire Ready, FlagConv;
  wire [6:0] TimerOut;
  wire [6:0] TempTMR;
  wire FlagTMR, N0, N1, N2, N3, N4, N5, N6;
  wire N7, N8, N9, N10, N11, N14, N15, N16;
  wire N17, N18, N19, N20, N21, N22, N23, N24;
  wire N25, N26, N27, N29, N32, N33, N34, N35;
  wire N36, N37, N39, N40, N41, N42, N43, N44;
  wire N45, N46, N47, N48, N49, N50, N51, N52;
  wire N53, N54, N55, N69;
  QDFFRBS \TimerOut_reg[0] (.RB (N55), .CK (ClockT), .D (N49), .Q
       (TimerOut[0]));
  QDFFRBS \TimerOut_reg[1] (.RB (N55), .CK (ClockT), .D (N48), .Q
       (TimerOut[1]));
  QDFFRBS \TimerOut_reg[2] (.RB (N55), .CK (ClockT), .D (N47), .Q
       (TimerOut[2]));
  QDFFRBS \TimerOut_reg[3] (.RB (N55), .CK (ClockT), .D (N54), .Q
       (TimerOut[3]));
  QDFFRBS \TimerOut_reg[4] (.RB (N55), .CK (ClockT), .D (N53), .Q
       (TimerOut[4]));
  QDFFRBS \TimerOut_reg[5] (.RB (N55), .CK (ClockT), .D (N51), .Q
       (TimerOut[5]));
  QDFFRBS \TimerOut_reg[6] (.RB (N55), .CK (ClockT), .D (N50), .Q
       (TimerOut[6]));
  QDFFRBN \TempTMR_reg[2] (.RB (N55), .CK (ClockT), .D (N43), .Q
       (TempTMR[2]));
  QDFFRBN \TempTMR_reg[1] (.RB (N55), .CK (ClockT), .D (N41), .Q
       (TempTMR[1]));
  QDFFRBP \TempTMR_reg[0] (.RB (N55), .CK (ClockT), .D (N42), .Q
       (TempTMR[0]));
  QDFFRBN \TempTMR_reg[6] (.RB (N55), .CK (ClockT), .D (N45), .Q
       (TempTMR[6]));
  QDFFRBP \TempTMR_reg[5] (.RB (N55), .CK (ClockT), .D (N44), .Q
       (TempTMR[5]));
  QDFFRBN \TempTMR_reg[4] (.RB (N55), .CK (ClockT), .D (N40), .Q
       (TempTMR[4]));
  QDFFRBP \TempTMR_reg[3] (.RB (N55), .CK (ClockT), .D (N46), .Q
       (TempTMR[3]));
  MXL2HS g709(.S (N52), .A (N7), .B (N14), .OB (N54));
  QDFFRBN FlagTMR_reg(.RB (N55), .CK (ClockT), .D (N39), .Q (FlagTMR));
  MXL2HS g710(.S (N52), .A (N6), .B (N33), .OB (N53));
  MXL2HS g711(.S (N52), .A (N2), .B (N0), .OB (N51));
  MXL2HS g712(.S (N52), .A (N4), .B (N8), .OB (N50));
  MXL2HS g706(.S (N52), .A (N1), .B (N18), .OB (N49));
  MXL2HS g707(.S (N52), .A (N5), .B (N17), .OB (N48));
  MXL2HS g708(.S (N52), .A (N3), .B (N24), .OB (N47));
  QDFFRBS Ready_reg(.RB (N55), .CK (ClockT), .D (N52), .Q (Ready));
  NR2 g692(.I1 (N27), .I2 (N52), .O (N46));
  NR2 g684(.I1 (N52), .I2 (N37), .O (N45));
  NR2 g685(.I1 (N52), .I2 (N36), .O (N44));
  NR2 g714(.I1 (N25), .I2 (N52), .O (N43));
  NR2 g716(.I1 (TempTMR[0]), .I2 (N52), .O (N42));
  NR2 g718(.I1 (N19), .I2 (N52), .O (N41));
  NR2 g689(.I1 (N34), .I2 (N52), .O (N40));
  ND2 g717(.I1 (N69), .I2 (N29), .O (N39));
  INV6 g719(.I (N69), .O (N52));
  AOI12S g686(.A1 (TempTMR[6]), .B1 (N35), .B2 (TempTMR[5]), .O (N37));
  XNR2HS g688(.I1 (TempTMR[5]), .I2 (N35), .O (N36));
  XOR2HS g691(.I1 (TempTMR[4]), .I2 (N32), .O (N34));
  NR2P g693(.I1 (N33), .I2 (N32), .O (N35));
  INV1S g725(.I (N29), .O (FlagConv));
  XNR2HS g705(.I1 (N26), .I2 (TempTMR[3]), .O (N27));
  ND2P g715(.I1 (N26), .I2 (TempTMR[3]), .O (N32));
  ND2P g726(.I1 (N21), .I2 (N15), .O (N29));
  MUX2 g721(.S (N23), .A (TempTMR[2]), .B (N24), .O (N25));
  NR2T g723(.I1 (N24), .I2 (N23), .O (N26));
  NR2P g724(.I1 (N11), .I2 (N23), .O (N22));
  ND2 g727(.I1 (N9), .I2 (N10), .O (N21));
  INV2 g728(.I (N16), .O (N20));
  AOI22S g731(.A1 (N18), .A2 (TempTMR[1]), .B1 (N17), .B2 (TempTMR[0]),
       .O (N19));
  ND3 g729(.I1 (TempTMR[6]), .I2 (TempTMR[2]), .I3 (TempTMR[5]), .O
       (N16));
  AOI12S g730(.A1 (Reset), .B1 (StateP[0]), .B2 (StateP[1]), .O (N15));
  INV1S g737(.I (TempTMR[3]), .O (N14));
  ND2P g733(.I1 (TempTMR[1]), .I2 (TempTMR[0]), .O (N23));
  ND2 g735(.I1 (TempTMR[4]), .I2 (TempTMR[3]), .O (N11));
  NR2 g732(.I1 (Dcr), .I2 (Inc), .O (N10));
  NR2 g734(.I1 (StateP[0]), .I2 (StateP[1]), .O (N9));
  INV1S g740(.I (TempTMR[0]), .O (N18));
  INV1S g743(.I (TempTMR[6]), .O (N8));
  INV2 g736(.I (TempTMR[2]), .O (N24));
  INV1S g752(.I (TimerOut[3]), .O (N7));
  INV1S g751(.I (TimerOut[4]), .O (N6));
  INV1S g742(.I (TempTMR[4]), .O (N33));
  INV1S g746(.I (TimerOut[1]), .O (N5));
  INV1S g741(.I (TimerOut[6]), .O (N4));
  INV1S g748(.I (TimerOut[2]), .O (N3));
  INV1S g749(.I (TimerOut[5]), .O (N2));
  INV1S g750(.I (TimerOut[0]), .O (N1));
  INV1S g744(.I (Reset), .O (N55));
  INV1S g747(.I (TempTMR[1]), .O (N17));
  INV1S g745(.I (TempTMR[5]), .O (N0));
  MAOI1HP g2(.A1 (N22), .A2 (N20), .B1 (FlagTMR), .B2 (N29), .O (N69));
endmodule

