
// Generated by Cadence Encounter(R) RTL Compiler RC11.22 - v11.20-s017_1

// Verification Directory fv/SARTimerVerilog 

module SARTimerVerilog_TIMER6(Reset, ClockT, StateP, Inc, Dcr, Ready,
     TimerOut, FlagConv);
  input Reset, ClockT, Inc, Dcr;
  input [1:0] StateP;
  output Ready, FlagConv;
  output [5:0] TimerOut;
  wire Reset, ClockT, Inc, Dcr;
  wire [1:0] StateP;
  wire Ready, FlagConv;
  wire [5:0] TimerOut;
  wire [5:0] TempTMR;
  wire FlagTMR, N0, N1, N2, N3, N4, N5, N6;
  wire N7, N8, N9, N10, N11, N12, N13, N14;
  wire N15, N16, N17, N18, N21, N22, N24, N26;
  wire N28, N30, N35, N36, N37, N38, N39, N40;
  wire N41, N42, N43, N44, N45, N46, N47, N60;
  wire N61, N62, N63;
  QDFFRBS \TimerOut_reg[0] (.RB (N47), .CK (ClockT), .D (N46), .Q
       (TimerOut[0]));
  QDFFRBS \TimerOut_reg[1] (.RB (N47), .CK (ClockT), .D (N43), .Q
       (TimerOut[1]));
  QDFFRBS \TimerOut_reg[2] (.RB (N47), .CK (ClockT), .D (N45), .Q
       (TimerOut[2]));
  QDFFRBS \TimerOut_reg[3] (.RB (N47), .CK (ClockT), .D (N41), .Q
       (TimerOut[3]));
  QDFFRBS \TimerOut_reg[4] (.RB (N47), .CK (ClockT), .D (N42), .Q
       (TimerOut[4]));
  QDFFRBS \TimerOut_reg[5] (.RB (N47), .CK (ClockT), .D (N40), .Q
       (TimerOut[5]));
  QDFFRBN FlagTMR_reg(.RB (N47), .CK (ClockT), .D (N39), .Q (FlagTMR));
  MXL2HS g627(.S (N44), .A (N13), .B (N5), .OB (N46));
  MXL2HS g629(.S (N44), .A (N18), .B (N3), .OB (N45));
  MXL2HS g628(.S (N44), .A (N12), .B (N2), .OB (N43));
  MXL2HS g631(.S (N44), .A (N24), .B (N0), .OB (N42));
  MXL2HS g630(.S (N44), .A (N26), .B (N4), .OB (N41));
  MXL2HS g632(.S (N44), .A (N1), .B (N6), .OB (N40));
  QDFFRBN \TempTMR_reg[3] (.RB (N47), .CK (ClockT), .D (N60), .Q
       (TempTMR[3]));
  QDFFRBP \TempTMR_reg[4] (.RB (N47), .CK (ClockT), .D (N62), .Q
       (TempTMR[4]));
  QDFFRBN \TempTMR_reg[2] (.RB (N47), .CK (ClockT), .D (N61), .Q
       (TempTMR[2]));
  QDFFRBN \TempTMR_reg[5] (.RB (N47), .CK (ClockT), .D (N35), .Q
       (TempTMR[5]));
  QDFFRBP \TempTMR_reg[1] (.RB (N47), .CK (ClockT), .D (N37), .Q
       (TempTMR[1]));
  QDFFRBP \TempTMR_reg[0] (.RB (N47), .CK (ClockT), .D (N38), .Q
       (TempTMR[0]));
  ND2 g636(.I1 (N44), .I2 (N28), .O (N39));
  NR2 g637(.I1 (TempTMR[0]), .I2 (N36), .O (N38));
  NR2 g638(.I1 (N14), .I2 (N36), .O (N37));
  NR2 g639(.I1 (N63), .I2 (N36), .O (N35));
  QDFFRBS Ready_reg(.RB (N47), .CK (ClockT), .D (N36), .Q (Ready));
  INV4 g641(.I (N36), .O (N44));
  ND2F g642(.I1 (N22), .I2 (N30), .O (N36));
  OR2P g646(.I1 (FlagTMR), .I2 (N28), .O (N30));
  INV1S g650(.I (N28), .O (FlagConv));
  ND3P g644(.I1 (N21), .I2 (TempTMR[4]), .I3 (TempTMR[5]), .O (N22));
  ND2P g651(.I1 (N15), .I2 (N11), .O (N28));
  NR2 g647(.I1 (N18), .I2 (N16), .O (N17));
  ND2P g652(.I1 (N9), .I2 (N10), .O (N15));
  NR2F g654(.I1 (N7), .I2 (N8), .O (N21));
  AOI22S g655(.A1 (N13), .A2 (TempTMR[1]), .B1 (N12), .B2 (TempTMR[0]),
       .O (N14));
  AOI12S g653(.A1 (Reset), .B1 (StateP[0]), .B2 (StateP[1]), .O (N11));
  NR2P g656(.I1 (Dcr), .I2 (Inc), .O (N10));
  NR2P g658(.I1 (StateP[0]), .I2 (StateP[1]), .O (N9));
  ND2 g660(.I1 (TempTMR[1]), .I2 (TempTMR[0]), .O (N16));
  ND2P g659(.I1 (TempTMR[1]), .I2 (TempTMR[3]), .O (N8));
  ND2P g657(.I1 (TempTMR[0]), .I2 (TempTMR[2]), .O (N7));
  INV1S g663(.I (Reset), .O (N47));
  INV1S g668(.I (TempTMR[3]), .O (N26));
  INV1S g664(.I (TempTMR[2]), .O (N18));
  INV1S g669(.I (TempTMR[0]), .O (N13));
  INV1S g661(.I (TimerOut[5]), .O (N6));
  INV1S g672(.I (TimerOut[0]), .O (N5));
  INV1S g666(.I (TimerOut[3]), .O (N4));
  INV1S g665(.I (TimerOut[2]), .O (N3));
  INV1S g662(.I (TempTMR[1]), .O (N12));
  INV1S g667(.I (TimerOut[1]), .O (N2));
  INV1S g671(.I (TempTMR[4]), .O (N24));
  INV1S g673(.I (TempTMR[5]), .O (N1));
  INV1S g670(.I (TimerOut[4]), .O (N0));
  MUXB2 g2(.S (N17), .A (TempTMR[3]), .B (N26), .EB (N36), .O (N60));
  MUXB2 g688(.S (N16), .A (N18), .B (TempTMR[2]), .EB (N36), .O (N61));
  MUXB2 g689(.S (N21), .A (TempTMR[4]), .B (N24), .EB (N36), .O (N62));
  AOI12S g690(.A1 (TempTMR[5]), .B1 (N21), .B2 (TempTMR[4]), .O (N63));
endmodule

